### ISSUE TITLE
How to exclude dirs from being recognized?

### ISSUE THREAD

**Issue by iHaveAstream** [GioF71/minidlna-docker#30]
Hi @GioF71 

first and foremost, many thanks for your nice work!
I've been using Twonky Server till now but it used to be quite unreliable recently, hence I found your minidlna-docker project and it seems to be quite fast. 
Regarding stability it's too early for me to judge about, but I'm sure it will be performing pretty well!

So, I am running this minidlna on my Synology NAS inside docker.
Typically, there is in each and every folder another folder (hidden one) that's called ```@eaDir```.
And I'm currently looking for a method how to exclude all of these, e.g. by adding some ENV variable to the container.
The reason why I want to exclude all ```@eaDir``` is because they do not contain real data (files) so to say, just "extended attributes".
And in the minidlna.log I thus get a flood of errors, for example:

```monitor.c:130: error: inotify_add_watch(/music/Neu/Full CD/@eaDir) [No space left on device]```

In Twonky Server UI there used to be an option to exclude desired folder via comma separated list.

So, is there already some (hidden) option to exclude dirs with a specific name or could you probably add such option as ENV variable?

Many thanks!

**Comment by GioF71** [comment]
Hello, thank you for the kind words.

About your issue, from what I understand, circumventing the issue by specifying all the other directories other than those `@eaDir` is to be considered impossible because those directories are at every level of the tree, am I right?

Looking at the [configuration options](https://manpages.debian.org/bookworm/minidlna/minidlna.conf.5.en.html) I don't see anything that fits your use case. I have also considerer the option to adopt union file systems but to my knowledge none can exclude directories using a configuration pattern. Maybe a custom vfs could do the trick, what that would be an entire project. Or, of course, a new implementation on the MiniDLNA codebase could add the feature you need, but the project does not look very actively developed these days.

That said, if the most relevant issue is the flood of errors in the log file, you can try to reduce the log level to "fatal" using the `MINIDLNA_LOG_LEVEL` variable. That would exclude those errors.

Finally, have you considerer alternatives to MiniDLNA?
What is the content you are sharing with MiniDLNA? Audio, Video, Photo, all of them? There are probably options available, for example Jellyfin, which can also expose the contents using DLNA. For music, you might use [upmpdcli with uprcl](https://github.com/GioF71/audio-tools/tree/main/media-servers/uprcl), or run some Subsonic Servers (see [Navidrome](https://github.com/navidrome/navidrome) or [Lightweight Music Server](https://github.com/epoupon/lms) and then expose them using the [subsonic plugin for subsonic](https://github.com/GioF71/audio-tools/tree/main/media-servers/subsonic).

**Comment by iHaveAstream** [comment]
Hi,
thanks for your fast reply. I'm using it for music only at this point.

I think I found the "solution" already which is related to an increased number of ```max_user_watches```
The default value on my NAS is 8192 and I've now increased it to 204800.

Suddenly and after another restart of miniDLNA container, there are no more any such ```warn``` level log errors.
So it seems to be solved by this.

Just out of curiosity, why is there the following ```warn``` level log entry present: 
```
minidlna.c:521: warn: Unset locale
```

Thanks!

**Comment by GioF71** [comment]
Hi, well I tried set the variables LANG, LANGUAGE and LC_ALL but no result. Probably some packages are missing. It's probably something that can be solved, I will open an issue for this and see when I can implement it. I think the warning is mostly harmless anyway...

Please consider starring the repo if you like the work!

**Comment by iHaveAstream** [comment]
Alright, thank you and I've already starred this repo :)
